UtilizandoRazor/Controllers/HtmlHelperController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UtilizandoRazor.Models;

namespace UtilizandoRazor.Controllers
{
    public class HtmlHelperController : Controller
    {


        public ActionResult Lista()
        {
            ViewBag.tipoDeConta = new SelectList(
                new Conta().listaTipoConta(), "idConta", "tipoDeConta"
                );

            return View();
        }

        public ActionResult Lista2()
        {
            var tipos = new Collection<string>
            {
                "conta corrente",
                "conta poupança",
                "conta salário"
            };
            ViewBag.tipoDeConta = tipos;

            return View();
        }



        // GET: HtmlHelper
        public ActionResult Index()
        {
            return View();
        }

        // GET: HtmlHelper/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HtmlHelper/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HtmlHelper/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HtmlHelper/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HtmlHelper/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HtmlHelper/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HtmlHelper/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UtilizandoRazor/Controllers/ViewDataBagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UtilizandoRazor.Models;

namespace UtilizandoRazor.Controllers
{
    public class ViewDataBagController : Controller
    {
        // GET: ViewDataBag
        public ActionResult Index()
        {
            ViewData["dataAtual"] = DateTime.Now.ToLongDateString();
            ViewBag.horaAtual = DateTime.Now.ToLongTimeString();

            return View();
        }

        /* forma de transporte de objetos com razor: viewdata e viewbag*/
        public ActionResult exemplo2()
        {
            var conta = new Conta()
            {
                idConta = 1,
                numeroConta = 001659,
                nomeCliente = "joão da silva",
                saldoAtual = 1535.0,
                limiteChequeEspecial = 500.0,
                dataEntrada = DateTime.Now.Date
            };

            ViewData["conta"] = conta;
            ViewBag.conta = conta;

            return View();
        }

        /* forma 2 de transporte de objetos com razor: strongly typed views stv*/
        public ActionResult exemplo3()
        {
            var conta = new Conta
            {
                idConta = 2,
                numeroConta = 0332,
                nomeCliente = "Maria Silva",
                saldoAtual = 2400.0,
                limiteChequeEspecial = 1400.0,
                dataEntrada = DateTime.Now.Date
            };

            return View(conta);
        }


        // GET: ViewDataBag/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ViewDataBag/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ViewDataBag/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ViewDataBag/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ViewDataBag/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ViewDataBag/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ViewDataBag/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UtilizandoRazor/Views/HtmlHelper/Index.cshtml
@model UtilizandoRazor.Models.Conta


@{
    ViewBag.Title = "Index";
}

<h2>Html Helper</h2>

<h2>HTML ActionLink</h2>
@Html.ActionLink("link com HTML Helpers", "exemplo3", "ViewDataBag")


<h2>HTML Forms</h2>
@{ Html.BeginForm();}

<!-- ITENS DO FORMULARIO -->

@{ Html.EndForm();}

@using (Html.BeginForm())
{
    <!-- ITENS DO FORMULARIO -->
}

<!-- informando parametros de requisição manualmente -->
@using (Html.BeginForm("exemplo2", "ViewDataBag"))
{
    <!-- ITENS DO FORMULARIO -->
}

<!-- HTML Checkbox -->
@Html.CheckBox("Ativo", "false")
@Html.CheckBox("Ativo", "false")

<!-- HTML TextBox -->
@Html.TextBox("Nome", "Digite o nome do cliente")

<!-- HTML TextArea -->
@Html.TextArea("observação", "Informações complementares")

<!-- HTML RadioButton -->
@Html.RadioButton("Estado", "Paraná", "false")
@Html.RadioButton("Estado", "Rio Grande do Sul", "true")
@Html.RadioButton("Estado", "Santa Catarina", "false")

<!-- HTML Hidden -->
@Html.Hidden("Identificador", 1)

<!-- HTML Password -->
@Html.Password("Password")

<h2>Componente checkbox tipado</h2>
<!-- variavel conta recebe uma referencia da classe Conta -->
@Html.CheckBoxFor(conta => conta.indicaAtivo)

@Html.TextAreaFor(conta => conta.observacao)

@Html.RadioButtonFor(conta => conta.tipoDeConta, "Conta Corrente")
@Html.RadioButtonFor(conta => conta.tipoDeConta, "Conta Poupança")
@Html.RadioButtonFor(conta => conta.tipoDeConta, "Conta Salário")

<br />

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Conta</legend>

        @Html.LabelFor(model => model.nomeCliente)
        @Html.TextBoxFor(model => model.nomeCliente)
        <br />

        @Html.LabelFor(model => model.nomeCliente)
        @Html.EditorFor(model => model.nomeCliente)
    </fieldset>
}

<br/>


@using (Html.BeginForm())
{
    <fieldset>
        <legend>Conta</legend>
        @Html.EditorForModel()
    </fieldset>
}


<br />

UtilizandoRazor/Views/HtmlHelper/Lista.cshtml
@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>


@Html.DropDownList("tipoDeConta", String.Empty);

UtilizandoRazor/Views/HtmlHelper/Lista2.cshtml
@{
    ViewBag.Title = "Lista2";
}

<h2>Lista2</h2>

@Html.DropDownList("tipoDeConta", String.Empty);